sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t reachrajin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true reachrajin/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-185867365933"
  bucket_path: "docker" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acccess_key: "$AWS_SECRET_KEY"