sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t reachrajin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true reachrajin/docker-react npm run test